# ---------------------------------------------------------
# Oh My Zsh
# ---------------------------------------------------------
# Path to your oh-my-zsh configuration.
export ZSH="$HOME/.oh-my-zsh"


# ---------------------------------------------------------
# Theme
# ---------------------------------------------------------
if [ -f ~/.zsh.theme ]; then
    source ~/.zsh.theme
else
    ZSH_THEME="materialshell"
fi

source $ZSH/oh-my-zsh.sh


# ---------------------------------------------------------
# OMZ Plugins
# ---------------------------------------------------------
# Plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
    git
    zsh-syntax-highlighting
)


# ---------------------------------------------------------
# Common Shell Dotfiles
# ---------------------------------------------------------
for file in $HOME/.shell_{exports,aliases,functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/bin/virtualenvwrapper.sh


# ---------------------------------------------------------
# Local zshrc
# ---------------------------------------------------------
[ -f ~/.zsh.local ] && source ~/.zsh.local || true
